### ISSUE TITLE
Is Alter-Native support p/invoke?

### ISSUE THREAD

**Issue by SirusDoma** [AlexAlbala/Alter-Native#4]
I have question before trying out this project.
I developed game based on <a href="http://www.opentk.com">OpenTK</a> and it uses AutoGenerated attributes

and it calls OpenGL native functions via p/invoke.
The question is, is this project support with binaries that uses p/invoke feature?

**Comment by AlexAlbala** [comment]
Hi SirusDoma

This is a good question :)

We have been working in this feature in the .NET micro framework environment. Actually the resulting code is supporting P/Invoke features but you may take care about using it because there are a lot of options not supported yet.

I encourage you to make a simple program test in order to view if AlterNative fit your needs, if not, you can contact me here and I will be pleased to work with you as possible in order to make it worth for you if possible.

Thank you
